spring:
  profiles: stage
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/junglee?currentSchema=public
    username: postgres
    password: NEW_PASSWORD
    